// Generated by npm run themes:generate.
export const APP_THEMES = ["default","dark","up-and-up","baseball","neon","monokai","sunset","fall"] as const;
export type AppTheme = typeof APP_THEMES[number];
export const THEME_OPTIONS: Array<{ value: AppTheme; label: string }> = [
  {
    "value": "default",
    "label": "Light"
  },
  {
    "value": "dark",
    "label": "Dark"
  },
  {
    "value": "up-and-up",
    "label": "Up & Up"
  },
  {
    "value": "baseball",
    "label": "Baseball"
  },
  {
    "value": "neon",
    "label": "Neon"
  },
  {
    "value": "monokai",
    "label": "Monokai"
  },
  {
    "value": "sunset",
    "label": "Sunset"
  },
  {
    "value": "fall",
    "label": "Fall"
  }
];
