export const THEME_TOKEN_CONTRACT = [
  '--color-surface-canvas',
  '--color-surface-default',
  '--color-surface-raised',
  '--color-surface-sunken',
  '--color-surface-inverse',
  '--color-surface-inverse-subtle',
  '--color-surface-overlay',
  '--color-on-canvas',
  '--color-on-surface',
  '--color-content-secondary',
  '--color-content-muted',
  '--color-on-inverse',
  '--color-on-inverse-muted',
  '--color-on-inverse-danger',
  '--color-border-subtle',
  '--color-border-default',
  '--color-border-strong',
  '--color-border-focus',
  '--color-border-on-inverse',
  '--color-accent-primary',
  '--color-on-accent-primary',
  '--color-accent-primary-subtle',
  '--color-on-accent-primary-subtle',
  '--color-border-accent-primary',
  '--color-hover-on-accent-primary',
  '--color-accent-secondary',
  '--color-on-accent-secondary',
  '--color-accent-secondary-subtle',
  '--color-on-accent-secondary-subtle',
  '--color-border-accent-secondary',
  '--color-hover-on-accent-secondary',
  '--color-interactive-primary',
  '--color-on-interactive-primary',
  '--color-interactive-primary-hover',
  '--color-interactive-secondary',
  '--color-on-interactive-secondary',
  '--color-interactive-secondary-hover',
  '--color-interactive-subtle',
  '--color-on-interactive-subtle',
  '--color-interactive-subtle-hover',
  '--color-interactive-selected',
  '--color-on-interactive-selected',
  '--color-border-selected',
  '--color-interactive-positive',
  '--color-on-interactive-positive',
  '--color-interactive-positive-hover',
  '--color-border-positive',
  '--color-interactive-danger',
  '--color-on-interactive-danger',
  '--color-interactive-danger-hover',
  '--color-feedback-info-surface',
  '--color-on-feedback-info',
  '--color-feedback-info-border',
  '--color-feedback-success-surface',
  '--color-on-feedback-success',
  '--color-feedback-success-border',
  '--color-feedback-danger-surface',
  '--color-on-feedback-danger',
  '--color-feedback-danger-border',
  '--color-transparent',
  '--color-overlay-backdrop',
  '--color-hover-on-inverse',
  '--color-chart-series-1',
  '--color-chart-series-2',
  '--color-chart-series-3',
  '--color-chart-series-1-fill',
  '--color-chart-series-2-fill',
  '--color-chart-series-3-fill',
  '--shadow-subtle',
  '--shadow-soft',
  '--shadow-medium',
  '--shadow-strong',
  '--shadow-button-inset',
  '--shadow-button-hover-inset',
  '--shadow-button-pressed',
  '--shadow-control-inset',
  '--image-surface-canvas',
  '--image-surface-hero',
  '--image-surface-accent',
] as const;

export const BRAND_IMAGE_TOKEN_CONTRACT = [
  '--image-brand-mark',
  '--image-brand-mark-alternate',
  '--image-brand-wordmark',
] as const;

export const THEME_CONTRAST_PAIRS = [
  ['--color-surface-canvas', '--color-on-canvas'],
  ['--color-surface-default', '--color-on-surface'],
  ['--color-surface-raised', '--color-on-surface'],
  ['--color-surface-sunken', '--color-on-surface'],
  ['--color-surface-inverse', '--color-on-inverse'],
  ['--color-accent-primary', '--color-on-accent-primary'],
  ['--color-accent-primary-subtle', '--color-on-accent-primary-subtle'],
  ['--color-accent-secondary', '--color-on-accent-secondary'],
  ['--color-accent-secondary-subtle', '--color-on-accent-secondary-subtle'],
  ['--color-interactive-primary', '--color-on-interactive-primary'],
  ['--color-interactive-primary-hover', '--color-on-interactive-primary'],
  ['--color-interactive-secondary', '--color-on-interactive-secondary'],
  ['--color-interactive-secondary-hover', '--color-on-interactive-secondary'],
  ['--color-interactive-subtle', '--color-on-interactive-subtle'],
  ['--color-interactive-subtle-hover', '--color-on-interactive-subtle'],
  ['--color-interactive-selected', '--color-on-interactive-selected'],
  ['--color-interactive-positive', '--color-on-interactive-positive'],
  ['--color-interactive-positive-hover', '--color-on-interactive-positive'],
  ['--color-interactive-danger', '--color-on-interactive-danger'],
  ['--color-interactive-danger-hover', '--color-on-interactive-danger'],
  ['--color-feedback-info-surface', '--color-on-feedback-info'],
  ['--color-feedback-success-surface', '--color-on-feedback-success'],
  ['--color-feedback-danger-surface', '--color-on-feedback-danger'],
] as const;
