require('./theme-loader.cjs');
const fs = require('fs');
const path = require('path');
const { THEME_DEFINITIONS } = require('../src/themes/definitions.ts');
const { compileTheme } = require('../src/themes/compiler.ts');
const check = process.argv.includes('--check');
const files = new Map();
const banner = '/* Generated by npm run themes:generate. Edit src/themes/definitions.ts instead. */\n';
const seen = new Set();
for (const theme of THEME_DEFINITIONS) {
  if (seen.has(theme.id)) throw new Error(`Duplicate theme ID: ${theme.id}`);
  seen.add(theme.id);
  const result = compileTheme(theme);
  if (!result.valid) throw new Error(`${theme.id}:\n${result.diagnostics.filter(d => d.severity === 'error').map(d => d.message).join('\n')}`);
  files.set(`src/styles/theme-${theme.id}.css`, `${banner}[data-theme='${theme.id}'] {\n  color-scheme: ${theme.mode};\n${Object.entries(result.tokens).sort(([a], [b]) => a.localeCompare(b, 'en')).map(([key, value]) => `  ${key}: ${value};`).join('\n')}\n}\n`);
}
files.set('src/styles/themes.generated.css', banner + THEME_DEFINITIONS.map(t => `@import './theme-${t.id}.css';`).join('\n') + '\n');
files.set('src/themes/registry.generated.ts', `// Generated by npm run themes:generate.\nexport const APP_THEMES = ${JSON.stringify(THEME_DEFINITIONS.map(t => t.id))} as const;\nexport type AppTheme = typeof APP_THEMES[number];\nexport const THEME_OPTIONS: Array<{ value: AppTheme; label: string }> = ${JSON.stringify(THEME_DEFINITIONS.map(t => ({ value: t.id, label: t.name })), null, 2)};\n`);
let stale = false;
for (const [relative, text] of files) {
  const filename = path.resolve(__dirname, '..', relative);
  if (check) {
    if (!fs.existsSync(filename) || fs.readFileSync(filename, 'utf8').replace(/\r\n/g, '\n') !== text) {
      console.error(`Stale generated file: ${relative}`); stale = true;
    }
  } else fs.writeFileSync(filename, text);
}
if (stale) { console.error('Run npm run themes:generate and review the result.'); process.exitCode = 1; }
else console.log(`${check ? 'Verified' : 'Generated'} ${THEME_DEFINITIONS.length} themes and registry.`);
